# Generated by Django 2.2 on 2023-07-09 05:42

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('numeroProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('numeroMenu', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('fechaCreacion', models.DateField()),
                ('producto', djongo.models.fields.ArrayReferenceField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.productos')),
            ],
        ),
    ]
